# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       rsync
Summary:    A program for synchronizing files over a network
Version:    3.0.8
Release:    0
Group:      Applications/Internet
License:    GPLv3+
URL:        http://rsync.samba.org/
#Source0:    http://rsync.samba.org/ftp/rsync/src/rsync-%{version}.tar.gz
Source0:    rsync_%{version}.orig.tar.gz
Source1:    rsync.xinetd
Source100:  rsync.yaml
BuildRequires:  pkgconfig(popt)
BuildRequires:  libacl-devel
BuildRequires:  libattr-devel


%description
Rsync uses a reliable algorithm to bring remote and host files into
sync very quickly. Rsync is fast because it just sends the differences
in the files over the network instead of sending the complete
files. Rsync is often used as a very powerful mirroring process or
just as a more capable replacement for the rcp command. A technical
report which describes the rsync algorithm is included in this
package.



%package support
Summary:    Support files for rsync
Group:      Applications/System
Requires:   %{name} = %{version}-%{release}

%description support
Support filrs for rsync



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install
mkdir -p %{buildroot}/etc/xinetd.d
cp -a %{SOURCE1} %{buildroot}/etc/xinetd.d


# >> install post
# << install post









%files
%defattr(-,root,root,-)
# >> files
%doc COPYING README
%config(noreplace) /etc/xinetd.d/rsync
%{_prefix}/bin/rsync
%doc %{_mandir}/man1/rsync.1*
%doc %{_mandir}/man5/rsyncd.conf.5*
# << files


%files support
%defattr(-,root,root,-)
# >> files support
# << files support

%changelog
* Thu Apr 21 2011 Patrick McCarty <patrick.mccarty@linux.intel.com> - 3.0.8
- Fix .yaml file for spectacle 0.22
- Update to version 3.0.8, which addresses BMC#15098 (CVE-2011-1097):
  using certain recursion, deletion, and ownership options allows
  remote rsync servers to cause a DoS.
* Thu Feb 11 2010 Anas Nashif <anas.nashif@intel.com> - 3.0.7
- Use spectacle
- Split package: support for all the support scripts
- Fixed rpmlint errors
- Update to 3.0.7
* Tue Sep  1 2009 Auke Kok <auke-jan.h.kok@intel.com> - 3.0.6
- Fix spec-builder "Extras" keyword usage.
* Wed Aug 26 2009 Jian-feng Ding <jian-feng.ding@intel.com> 3.0.6
- Update to version 3.0.6
* Sun Apr 12 2009 Anas Nashif <anas.nashif@intel.com> 3.0.5
- Remove default BuildRequires
* Sat Feb  7 2009 Arjan van de Ven <arjan@linux.intel.com> 3.0.5
- Update to version 3.0.5
* Wed Dec 17 2008 Arjan van de Ven <arjan@linux.intel.com> 3.0.2
- Clean up the spec
* Tue Dec 16 2008 Anas Nashif <anas.nashif@intel.com> 3.0.2
- Fixed rpmlint errors in Summary tag
